import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container1 from '../component/Container1'
import Container2 from '../component/Container2'
import Container3 from '../component/Container3'
import Example from './List'
import Navbar from '../component/Navbar'

const Home=()=> {
  return (
    <>
    
      <Head>
        <title>Medical Healthcare Solution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>

      <main className={styles.main}>
        <Container1/>
        <Container2/>
        <Container3/>
        {/* <Example/> */}
      </main>
      <div>
        
      </div>
        
        
    </>
  )
}

export default Home